platform :ios, '15.0'

use_frameworks!

workspace 'LucidDreaming.xcworkspace'

project 'LucidDreaming.xcodeproj'

target 'LucidDreaming' do
  pod 'Shared', :path => '../shared'
end

# SwiftUI and Combine are included in iOS SDK
